### PR TITLE
Fix all clippy warnings

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
At least for me, Clippy now doesn't complain about anything.

### CODE REVIEW

**Comment by linusg** [comment]
Can you rebase this please to ensure the stuff I just merged doesn't make it complain again? Then we can enforce it asap :)

**Comment by kleinesfilmroellchen** [comment]
See #169, imho we should make most Clippy stuff we care about a hard error. I'm working on integer overflow checking rn but yes, will do in a moment

**Comment by kleinesfilmroellchen** [comment]
@linusg rebased and fixed a lint in your commit :^)

**Comment by linusg** [comment]
That wasn't my commit, but thanks :smile:

**Pull request merged**
