### PR TITLE
editor: Add syntax highlighting for Sublime Text

### PR DESCRIPTION
**Pull request by CrystalSage**
Add syntax highlighting for Sublime Text. It should cover most of the 
syntax and any that might be introduced in the future. 

Instructions included in README.

### CODE REVIEW

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
Very nice!

Been testing this out, and it looks pretty good. I browsed through a few of the files in `samples/` and found a few missing things though:

Only the first enum value is highlighted: (samples/enums/parse.jakt)
image

`throw`, `throws` and `class` aren't highlighted. (samples/classes/throwing_method.jakt)

`weak` isn't highlighted. (samples/weak/basic.jakt)

**Comment by CrystalSage** [comment]
Ah. Noted! 

Can I fix those issues in subsequent PRs?  Making more commits in this PR means I'd have to squash them and I mess up a lot while squashing.

**Comment by juniorrantila** [comment]
> Ah. Noted! 
> 
> 
> 
> Can I fix those issues in subsequent PRs?  Making more commits in this PR means I'd have to squash them and I mess up a lot while squashing.

Since this is only one commit, you can modify it by doing
```
git add the-files-that-changed
git commit --amend
git push --force
```

**Comment by CrystalSage** [comment]
Done. Fixed everything @AtkinsSJ found to be broken. Thank you @juniorrantila!

**Pull request merged**
