### PR TITLE
jakttest: Check for selfhost & binary modified times before recompiling

### PR DESCRIPTION
**Pull request by cybergsus**

### CODE REVIEW

**Comment by cybergsus** [comment]
Something looks wrong revising this, please don't merge.

**Comment by cybergsus** [comment]
OK, it was that `sort` gave them in ascending order, so I used `-r` to get the latest one

**Comment by cybergsus** [comment]
Hmm, we have to check *all* the files under `selfhost/`. Reason behind this is that the directories' mtime is not updated when you update one of their inner files.

**Comment by cybergsus** [comment]
I guess an `any file under selfhost/*.jakt` is newer than `build/main` could work better, perhaps.

**Comment by cybergsus** [comment]
PD I also forgot to remove the commented `cargo run`

**Comment by jntrnr** [comment]
Latest main should have the CI errors fixed

**Pull request merged**
