### PR TITLE
codegen: Generate code for generic classes

### PR DESCRIPTION
**Pull request by mmeeaallyynn**
Generics are mostly working for structs and enums, but generic classes were not considered in the code for the most part.  
This should fix them for the most part. The only thing missing is type inference when accessing members, but I feel like this is out of scope for this pull request.

### CODE REVIEW

**Comment by jntrnr** [comment]
@mmeeaallyynn - thanks for the PR. Looks like you'll need to run it through `cargo fmt` to use the standard code formatting.

**Comment by mustafaquraish** [comment]
Please update the tests to follow the new format from 99a337b5734ac8f8c74ecdcb545dfe9cabde956d

Also, please squash your commits, we shouldn't be failing CI after any single commit in your PR.

**Comment by Hendiadyoin1** [comment]
It seems like you have rebased/pulled `main` ontop of your changes instead of the other way around,
please rebase your changes onto `main` instead

**Comment by mmeeaallyynn** [comment]
Thanks for the pointer, this did seem off to me after looking at other PRs.

**Comment by AtkinsSJ** [comment]
Closed as this is a change for the now-gone Rust-based compiler. Feel free to port your changes to the new compiler, if they're not already added, and open a new PR. :^)

**Pull request closed without merging**
