### PR TITLE
Replace occurences of first boolean with iterator enumerate (codegen)

### PR DESCRIPTION
**Pull request by Caleb-o**
This takes advantage of Rusts iterators, to remove the need of an extra boolean to track the first entry in a loop. This also removes an else branch to set the boolean state. There is one instance in ```codegen_function``` where this method may need some tweaks, but it was left as-is.

### CODE REVIEW

**Review by linusg — CHANGES_REQUESTED** [review]
Please squash these fixup commits

**Comment by Caleb-o** [comment]
I believe that did the job

**Comment by linusg** [comment]
- occurances -> occurrences
- No need to say "squash" in the commit message
- This has a conflict

**Comment by Caleb-o** [comment]
Oh whoops! This is also my first PR, so I'm new to the process. The recent commits have made additions to codegen, so I need to update it.

**Comment by linusg** [comment]
please squash these again

**Comment by Caleb-o** [comment]
I can't seem to squash down to a single commit (any further than I have) because of the merge from the latest commits.

**Comment by Caleb-o** [comment]
Will the current squashed version work or does it need to go further? The re-merge with main makes it so I can't squash it down any further. Is there a way to go further or will this work? I'm still new to PRs.

**Comment by linusg** [comment]
> Will the current squashed version work or does it need to go further?

No merge or fixup commits please :)

**Comment by Caleb-o** [comment]
I won't be able to do much more at this point, as it's now 4am. What's the next step because I'm not sure how to get this merged. Do I just reimplement my changes on the latest and submit another PR? I can't squash the commits down any more than it is, so I'm not sure what else to do. 

It was submitted not long before a bunch of changes to the codegen, so it had conflicts. I managed to merge the latest to fix all the conflicts, so the squash won't work because I needed to pull in the latest.

Could you elaborate on what is required, as I'm not sure how to proceed without starting a new fork and PR.

**Comment by Caleb-o** [comment]
I'm going to close this as it isn't really a significant change.

**Pull request closed without merging**
