### PR TITLE
typechecker: Add type hint for match statement return type

### PR DESCRIPTION
**Pull request by robryanx**
Previously for an Optional match you would need
```
let b = match a {
    Bar => Some(2)
    Baz => {
        let ret: i64? = None

        yield ret
    }
}
```

With a type hint it can now be written as
```
let b: i64? = match a {
    Bar => 2
    Baz => None
}
```

Also adds numeric inference on optional types.

### CODE REVIEW

**Comment by alimpfard** [comment]
:thinking: this should be allowed currently as well afaik?
```
let b = match a {
    Bar => Some(2)
    Baz => None
}
```

Propagating a type hint is nice though, +1 for making it work the expected way.

**Comment by robryanx** [comment]
> thinking this should be allowed currently as well afaik?
> 
> ```
> let b = match a {
>     Bar => Some(2)
>     Baz => None
> }
> ```
> 
> Propagating a type hint is nice though, +1 for making it work the expected way.

Yeah interesting, it does.
What I was seeing was that it doesn't work when yielding from a block
```
let b = match a {
        Bar => Some(2)
        else => {
            yield None
        }
    }
```
I'll look into what the difference is there.

**Comment by alimpfard** [comment]
Ah! Yield doesn't get the type hint as it's in a block, which doesn't accept one

**Comment by jntrnr** [comment]
@alimpfard - is the fix here that the type hint should go into the block for a match so any `yield` in it can see it?

**Comment by alimpfard** [comment]
I guess, we could pass it in as `yield_type_hint: TypeId?`

**Comment by robryanx** [comment]
> I guess, we could pass it in as `yield_type_hint: TypeId?`

Yeah, looking into something like that to see if that works with everything else.

**Comment by robryanx** [comment]
Updated now to include yield type hint.

**Pull request merged**
