### PR TITLE
selfhost/typechecker: Fix error about types not matching

### PR DESCRIPTION
**Pull request by lanmonster**

### CODE REVIEW

**Comment by lanmonster** [comment]
> 

CheckedExpression.span is reporting an error that it expects a `Span` but is getting a `Span?` from the `Defer` branch. The expected and actual types are flipped, but this change makes the function return `Span?` in every case.

**Comment by awesomekling** [comment]
Where is this error reported?

**Comment by lanmonster** [comment]
in VSCode
image

**Comment by lanmonster** [comment]
Oops! I just needed to `meta/update-vscode-extension.sh`.

**Pull request closed without merging**
